### ISSUE TITLE
unsatisfied requirements for Minuit2_Julia_Wrapper_jll 

### ISSUE THREAD

**Issue by mmikhasenko** [jstrube/Minuit2.jl#2]
just wanted to play around but got some problems on the installation step
```REPL
ERROR: Unsatisfiable requirements detected for package Minuit2_Julia_Wrapper_jll [65cff058]:                             Minuit2_Julia_Wrapper_jll [65cff058] log:                                                                               
├─Minuit2_Julia_Wrapper_jll [65cff058] has no known versions!                                                           
└─restricted to versions * by Minuit2 [37821647] — no versions left                                                       
     └─Minuit2 [37821647] log:                                                                                                 
          ├─possible versions are: 0.1.0 or uninstalled                                                                            
          └─Minuit2 [37821647] is fixed to version 0.1.0   
```

perhaps, the answer is in here (?)
```julia
@wrapmodule(Minuit2_Julia_Wrapper_jll.minuit2wrap_path)
function __init__()
     @initcxx
end
```

**Comment by mmikhasenko** [comment]
ok, found the c++ repo, `https://github.com/jstrube/Minuit2_Julia_Wrapper`
Still have not figured out what to do with it to make the package manager happy

**Comment by jstrube** [comment]
Take a look at the readme of the Minuit2_Julia_Wrapper repo. If you run
that line, it'll compile the code and put it into your ~/.julia/dev folder.
Then, you need to go into the package manager and `dev
Minuit2_Julia_Wrapper_jll`.
That should do the trick.

**Comment by jstrube** [comment]
I've created a repo where I uploaded some artifacts: https://github.com/jstrube/Minuit2_Julia_Wrapper_jll.jl
I'm not sure how to download the artifacts automatically from that location, but I think it just needs a path change in one of the toml files. (Maybe artifacts/Override.toml). I've added a pointer to the README, and I hope it helps.

**Comment by jstrube** [comment]
I think this is no longer an issue now since the wrapper is built on Yggdrasil. Please feel free to re-open if this is still an issue.

**Comment by mmikhasenko** [comment]
ok, thanks, will check it out
